#!/bin/bash

# Coloring
TM_BRIGHT="\033[1m"
TM_DARK="\033[2m"
BG_BLUE="\033[44m "
TX_YELLOW="\033[33m"
RESET="\033[m"

TEXT01="${TM_BRIGHT}${TM_DARK}"
DOCKER01="${BG_BLUE}${TM_BRIGHT}"

echo -e "            "
echo -e "PANDAS          "
echo -e "${DOCKER01}~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~${RESET}"
echo -e "BASIC COMMANDS"
echo -e "  ${TEXT01}df.head()                                  ${RESET} \t${TX_YELLOW}See top sample of dataframe${RESET}"
echo -e "  ${TEXT01}df.head(5)                                 ${RESET} \t${TX_YELLOW}See top 5 rows  of dataframe${RESET}"
echo -e "  ${TEXT01}df[:5]                                     ${RESET} \t${TX_YELLOW}See top 5 rows  of dataframe${RESET}"
echo -e "  ${TEXT01}df.tail(5)                                 ${RESET} \t${TX_YELLOW}See bottom 5 rows  of dataframe{$RESET}"
echo -e "  ${TEXT01}df.shape                                   ${RESET} \t${TX_YELLOW}Dimensions of dataframe, i.e. number of row and columns${RESET}"
echo -e "  ${TEXT01}df.size                                    ${RESET} \t${TX_YELLOW}Rows * columns${RESET}"
echo -e "  ${TEXT01}len(df)                                    ${RESET} \t${TX_YELLOW}number of rows"
echo -e "  ${TEXT01}df.columns                                 ${RESET} \t${TX_YELLOW}returns Index Object(array like) containing column names"
echo -e "  ${TEXT01}df.columns[0]                              ${RESET} \t${TX_YELLOW}name of first dimension"
echo -e "  ${TEXT01}df.loc[1]                                  ${RESET} \t${TX_YELLOW}returns Series Object, giving a rows values"
echo -e "  ${TEXT01}df['Column Name']                          ${RESET} \t${TX_YELLOW}returns Series Object, with all the dimension values"
echo -e "  ${TEXT01}df['Column Name'][:5]                      ${RESET} \t${TX_YELLOW}returns Series Object, with last 5 dimension values"
echo -e "  ${TEXT01}df['Column Name'][5]                       ${RESET} \t${TX_YELLOW}return the value in row 5"
echo -e "  ${TEXT01}df[['Col 01', 'Col 02']]                   ${RESET} \t${TX_YELLOW}returns Dataframe object, with just the dimensions given"
echo -e "  ${TEXT01}df.sort_values(['Column Name'])            ${RESET} \t${TX_YELLOW}returns Dataframe object, sorted on given dimension(Column Name)"
echo -e "  ${TEXT01}df['Column Name'].unique()                 ${RESET} \t${TX_YELLOW}returns numpy.ndarray object, giving unique values in a dimension"
echo -e "  ${TEXT01}df['Column Name'].value_counts()           ${RESET} \t${TX_YELLOW}returns Series object, giving a breakdown of unique values in a dimension"
