#!/bin/bash
dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
source "${dir}/config.sh"

tl="${bold}${tbg}${ttx}"
echo -e "${tl}                                                                 ${z}"
echo -e "${tl}                     -- KEYBOARD SHORTCUTS --                    ${z}"
echo -e "${tl}                                                                 ${z}"
echo -e "Icons:⌃ = ctrl, ⌘ = command, ⌥ = alt, ⇧ = shift"
echo -e "                   iTerm                    ||                     VSCode             "
echo -e " ⌘ + T          |  New Tab                  ||  Ctrl + z    |  Jump to terminal       "
echo -e " ⌘ + D          |  Split Window Vertically  ||  Ctrl + x    |  Jump to code           "
echo -e " ⌘ + ⇧ + D      |  Split Window Vertically  ||  ⌘ + ⌥ + up  |  Expand cursor          "
echo -e " ⌘ + ⌥ + arrow  |  Cycle through windows    ||  ⌘ + ⇧ + [   |  Toggle tabs            "
echo -e " Ctrl + K       |  Delete to end of line    ||              |                         "
echo -e "                                                                                      "
echo -e "                Google Chrome               ||                     Mac                "
echo -e " ⌘ + T          |  New Tab                  ||  ⌘ + space   |  spotlight search       "
echo -e " ⌘ + W          |  Close Tab                ||  ⌘ + Tab     |  switch between program "
echo -e " ⌘ + ⇧ + D      |  Split Window Vertically  ||  ⌘ + ,       |  Open Preferences       "
echo -e " ⌘ + ⌥ + arrow  |  Cycle through windows    ||  ⌘ + ⌥ + B   |  new iterm2 window here "
echo -e " ⌘ + 9          |  Move to last tab         ||  ⌘ + ⇧ + B   |  new iterm2 tab here    "
