#!/bin/bash
dir=$( cd "$(dirname "${BASH_SOURCE[0]}")" ; pwd -P )
source "${dir}/config.sh"

ttx="\033[38;2;123;66;188m" # terrafrom purple 123 66 188
tl="${bold}${tbg}${ttx}"
echo -e "${tl}                                                                 ${z}"
echo -e "${tl}                          -- TERRAFORM --                        ${z}"
echo -e "${tl}                                                                 ${z}"
echo -e "INSTALATION AND VESION CHANGE"
echo -e "  ${v}Install with brew                ${f}brew install tfenv && tfenv install 0.12.24 && tfenv use 0.12.24"
echo -e "  ${v}Install/use different version    ${f}tfenv install 0.13.1 && tfenv use 0.13.1${z}\n"

echo -e "COMMON COMMANDS"
echo -e "  ${v}Create terrafrom:                ${f}terrafrom init"
echo -e "  ${v}Create plan:                     ${f}terrafrom plan"
echo -e "  ${v}Create/modify infrustructure:    ${f}terrafrom apply"
echo -e "  ${v}  ditto with auto approve        ${f}terrafrom apply ${n}--auto-approve"
echo -e "  ${v}Deploy specified rerource:       ${f}terrafrom apply ${n}-target aws_instance.web_server_instance"
echo -e "  ${v}Specify variable value:          ${f}terraform apply ${n}-var ${t}\"<var name>=<var value>\""
echo -e "  ${v}Destroy resources:               ${f}terraform destroy"
echo -e "  ${v}Create terrafrom:                ${f}terraform destroy ${n}-target aws_instance.web_server_instance${z}"
echo -e "  ${v}Current version                  ${f}terrafrom version"

echo -e "\nFILES"
echo -e "${v}gets created after we run terraform init:   ${f}.terraform"
echo -e "${v}current state of the terraform deployment:   ${f}terraform.tfstate"

echo -e "${z}\nUseful Links"
echo -e "${v}Providers registry:                ${f}https://registry.terraform.io/browse/providers"
echo -e "${v}FCC Course:                        ${f}https://registry.terraform.io/browse/providers${z}"

echo -e "\nCODE SNIPPETS${z}"
echo -e "${bg}  ${r}resource ${t}\"<provider>_<resource_type>\" \"name\"${v} {                   ${z}"
echo -e "${bg}    config options.....(will be key/value pairs)                   ${z}"
echo -e "${bg}  }                                                                ${z}"
echo -e "${bg}                                                                   ${z}\n"
echo -e "${bg}  ${cc}# Configure the AWS Provider                                     ${z}"
echo -e "${bg}  ${r}provider ${t}\"aws\" ${v}{                                                 ${z}"
echo -e "${bg}    ${v}version = ${t}\"~> 3.0\"                                             ${z}"
echo -e "${bg}    ${v}region = ${t}\"eu-west-1\"                                           ${z}"
echo -e "${bg}    ${v}access_key = ${t}\"<aws-access-key>\"                                ${z}"
echo -e "${bg}    ${v}secret_key = ${t}\"<aws-secret-key>\"                                ${z}"
echo -e "${bg}  }                                                                ${z}"
echo -e "${bg}                                                                   ${z}"
echo -e "${bg}  ${r}resource ${t}\"aws_instance\" \"blynch-try-terraform\"${x} {                 ${z}"
echo -e "${bg}    ${v}ami          = ${t}\"ami-0943382e114f188e8\"                         ${z}"
echo -e "${bg}    ${v}instance_type = ${t}\"t2.micro\"                                     ${z}"
echo -e "${bg}    ${v}tags = {                                                       ${z}"
echo -e "${bg}      ${v}Name = ${t}\"blynch-try-terraform-tag\"                            ${z}"
echo -e "${bg}    }                                                              ${z}"
echo -e "${bg}  }                                                                ${z}"
